import { GameConfig } from './types';

export const gameConfig: GameConfig = {
  SEQUENCE_DISPLAY_TIME: 1000,
  SEQUENCE_TRANSITION_TIME: 300,
  INITIAL_TIME: 15,
  ENABLE_FEEDBACK_SOUND_ANIMATION: true,
  ENABLE_DIFFICULTY_INDICATOR: true,
  ENABLE_TUTORIAL: true,
  ENABLE_SHOW_SEQUENCE_ANIMATION: true,
  ENABLE_UNIFIED_STYLE: true,
  ENABLE_CONFETTI_ANIMATION: true,
};